version: '3.7'

services:
  rb_proxy:
    volumes:
      - ${RB_PROXY_CONFIG_FOLDER}/common:/etc/nginx/common
      - ${RB_DATA_FOLDER}/certbot/conf:/etc/letsencrypt
      - ${RB_DATA_FOLDER}/certbot/www:/var/www/certbot
    depends_on:
      - rb_webapp
      - rb_api
      - rb_www
      - rb_mobile

  rb_webapp:
    image: resorptionbidonvilles/frontend:${RB_WEBAPP_VERSION}
    container_name: rb_webapp
    networks:
      - rb_network
    expose:
      - 80
    env_file:
      - ./config/.env

  rb_mobile:
    image: resorptionbidonvilles/mobile:${RB_MOBILE_VERSION}
    container_name: rb_mobile
    networks:
      - rb_network
    expose:
      - 80
    env_file:
      - ./config/.env

  rb_www:
    image: resorptionbidonvilles/www:${RB_WWW_VERSION}
    container_name: rb_www
    networks:
      - rb_network
    expose:
      - 3000
    env_file:
      - ./config/.env

  rb_api:
    image: resorptionbidonvilles/api:${RB_API_VERSION}
    container_name: rb_api
    networks:
      - rb_network
    expose:
      - 80
    env_file:
      - ./config/.env
    depends_on:
      rb_database_data:
        condition: service_healthy
      rb_database_agenda:
        condition: service_healthy

  rb_certbot:
    image: certbot/certbot
    volumes:
      - ${RB_DATA_FOLDER}/certbot/conf:/etc/letsencrypt
      - ${RB_DATA_FOLDER}/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh"
    networks:
      - rb_network
    command: "-c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  rb_database_agenda:
    expose:
      - '27017-27019'
