version: '3.7'

services:
  rb_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: rb_proxy
    env_file:
      - ./config/.env
    ports:
      - 80:80
      - 443:443
    networks:
      - rb_network
    volumes:
      - ${RB_PROXY_CONFIG_FOLDER}/common/nginx.conf:/etc/nginx/nginx.conf
      - ${RB_PROXY_CONFIG_FOLDER}/http.conf:/etc/nginx/conf.d/http.conf
      - ${RB_PROXY_CONFIG_FOLDER}/templates/${RB_PROXY_TEMPLATE}:/etc/nginx/templates
      - ${RB_DEPLOY_DATA_FOLDER}/ssl:/etc/ssl

  rb_database_data:
    build:
      context: ./database
    container_name: rb_database_data
    volumes:
      - ${RB_DATABASE_DATA_FOLDER}:/var/lib/postgresql/data
      - rb_database_backups:${RB_DATABASE_LOCALBACKUP_FOLDER}
      - ${RB_DEPLOY_DATA_FOLDER}/rb_database_tmp:/tmp
    env_file:
      - ./config/.env
    ports:
      - ${RB_DATABASE_EXTERNAL_PORT}:5432
    networks:
      - rb_network
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 10s
      retries: 6

  rb_database_agenda:
    image: mongo:${RB_AGENDA_MONGO_VERSION}
    container_name: rb_database_agenda
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ${RB_AGENDA_DATA_FOLDER}:/data/db
    networks:
      - rb_network
    env_file:
      - ./config/.env

  rb_antivirus:
    image: ajilaag/clamav-rest
    container_name: rb_antivirus
    env_file:
      - ./config/.env
    mem_reservation: "2G"
    mem_limit: "3G"
    ports:
      - ${RB_CLAMAV_EXTERNAL_HTTP_PORT}:${RB_CLAMAV_INTERNAL_HTTP_PORT}
      - ${RB_CLAMAV_EXTERNAL_HTTPS_PORT}:${RB_CLAMAV_INTERNAL_HTTPS_PORT}
    user: clamav
    volumes:
      - rb_antivirus_data:/clamav
      - rb_antivirus_run:/run/clamav
      - rb_antivirus_log:/var/log/clamav
    networks:
      - rb_network
    healthcheck:
      test: clamscan --version
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  rb_database_backups:
    name: rb_database_backups
  rb_antivirus_data:
    name: rb_antivirus_data
  rb_antivirus_log:
    name: rb_antivirus_log
  rb_antivirus_run:
    name: rb_antivirus_run

networks:
  rb_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
